# Generated by Django 4.0.4 on 2022-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_mypost_image'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='post',
        ),
        migrations.AddField(
            model_name='account',
            name='posts',
            field=models.ManyToManyField(blank=True, to='post.mypost'),
        ),
    ]
