# Generated by Django 4.0.4 on 2022-04-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_remove_mypost_owner_remove_mypost_sibling'),
        ('account', '0002_remove_account_post_account_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='posts',
        ),
        migrations.AddField(
            model_name='account',
            name='Posts',
            field=models.ManyToManyField(blank=True, related_name='Posts', to='post.mypost'),
        ),
    ]
