# Generated by Django 4.0.4 on 2022-04-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('comments', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='categories',
            field=models.ManyToManyField(blank=True, max_length=3, to='category.mycategory'),
        ),
        migrations.AddField(
            model_name='mypost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comments'),
        ),
    ]
