# Generated by Django 4.0.4 on 2022-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_mypost_created_at_alter_mypost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/img/'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
