# Generated by Django 4.0.4 on 2022-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_mypost_created_at_alter_mypost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
