# Generated by Django 4.0.4 on 2022-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_mypost_created_at_alter_mypost_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='404Image.webp', upload_to='post/img/'),
        ),
    ]
