# Generated by Django 4.0.4 on 2022-04-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comments_post'),
        ('post', '0007_mypost_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='comments',
            field=models.ManyToManyField(blank=True, to='comments.comments'),
        ),
    ]
