# Generated by Django 4.0.4 on 2022-04-26 10:33

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='image',
            field=models.ImageField(default='404Image.webp', upload_to=post.models.user_directory_path),
        ),
    ]
