# Generated by Django 4.0.4 on 2022-04-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_mycategory_image'),
        ('post', '0009_alter_mypost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mypost',
            name='categories',
            field=models.ManyToManyField(max_length=3, to='category.mycategory'),
        ),
    ]
