# Generated by Django 4.0.4 on 2022-06-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_mypost_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypost',
            name='comments',
        ),
    ]
