# Generated by Django 4.0.4 on 2022-04-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCategory',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='category/static/category/img/')),
                ('myPosts', models.ManyToManyField(related_name='myPosts', to='post.mypost')),
            ],
        ),
    ]
