# Generated by Django 4.0.4 on 2022-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyCategory',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='category/img/')),
            ],
        ),
    ]
