# Generated by Django 4.0.4 on 2022-04-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycategory',
            name='image',
            field=models.ImageField(upload_to='category/img/'),
        ),
    ]
