# Generated by Django 4.0.4 on 2022-04-17 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_alter_mycategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycategory',
            name='myPosts',
        ),
    ]
